name: Build and Push portal-base Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'deployment/Dockerfile'
      - '.github/workflows/base-image.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069

      - name: Build and Push portal-base Image (amd64)
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: deployment
          push: true
          platforms: linux/amd64
          build-args: |
            PHP_VERSION=8.5
            DB_EXT=mysql
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/portal-base:8.5
            ${{ env.REGISTRY }}/${{ env.OWNER }}/portal-base:latest
